# Generated by Django 5.2.7 on 2025-11-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateTimeField()),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'ESTADOS UNIDOS'), ('BR', 'BRASIL')], max_length=200, null=True)),
            ],
        ),
    ]
